# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.uic import loadUi

from PyQt5.QtWidgets import QApplication

import xml.etree.ElementTree as etree



def create(pub,aut,tit,nb,année):

    publication=etree.Element("publication")

    auteur=etree.SubElement(publication,"auteur")

    titre=etree.SubElement(publication,"titre")

    nbpage=etree.SubElement(publication,"nbpage")

    year=etree.SubElement(publication,"year")

    publication.text=pub

    auteur.text=aut

    titre.text=tit

    nbpage.text=nb

    year.text=année

    b_xml = etree.tostring(publication)

    path=pub+".xml"
    with open(path, "wb") as f:

        f.write(b_xml)





def ajouter(pub,aut,titre,nb,année):

    if ((pub=='') or (aut=='') or titre=='' or nb==''or année==''):

        msg="le champ est obligatoire"

    else:

        create(pub,aut,titre,nb,année) 

        msg="bien ajouté"

    return msg 

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 55, 16))
        self.label_5.setObjectName("label_5")
        self.pub = QtWidgets.QLineEdit(Dialog)
        self.pub.setGeometry(QtCore.QRect(150, 30, 151, 22))
        self.pub.setObjectName("pub")
        self.auteurs = QtWidgets.QLineEdit(Dialog)
        self.auteurs.setGeometry(QtCore.QRect(150, 60, 151, 22))
        self.auteurs.setObjectName("auteurs")
        self.titre = QtWidgets.QLineEdit(Dialog)
        self.titre.setGeometry(QtCore.QRect(150, 90, 151, 22))
        self.titre.setObjectName("titre")
        self.nbr = QtWidgets.QLineEdit(Dialog)
        self.nbr.setGeometry(QtCore.QRect(150, 120, 151, 22))
        self.nbr.setObjectName("nbr")
        self.ann = QtWidgets.QLineEdit(Dialog)
        self.ann.setGeometry(QtCore.QRect(150, 150, 151, 22))
        self.ann.setObjectName("ann")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 0, 151, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 0, 101, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 180, 71, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 180, 81, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 180, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 249, 131, 21))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "nom publication"))
        self.label_2.setText(_translate("Dialog", "les auteurs"))
        self.label_3.setText(_translate("Dialog", "titre"))
        self.label_4.setText(_translate("Dialog", "nombre de pages"))
        self.label_5.setText(_translate("Dialog", "année"))
        self.label_6.setText(_translate("Dialog", " recherche"))
        self.pushButton_2.setText(_translate("Dialog", "ajouter"))
        self.pushButton_3.setText(_translate("Dialog", "modifier"))
        self.pushButton_4.setText(_translate("Dialog", "supprimer"))
        self.label_7.setText(_translate("Dialog", " "))


def play1():

    p=windows.pub.text()

    a=windows.auteurs.text()

    t=windows.titre.text()

    n=windows.nbr.text()

    aa=windows.ann.text()

    windows.label_7.setText(ajouter(p,a,t,n,aa))





app = QApplication([])

windows = loadUi ('interface.ui')

windows.show()

windows.pushButton_2.clicked.connect(play1)

app.exec_()
